# Generated by Django 4.1.3 on 2022-12-28 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MinLengthValidator(10)]
            ),
        ),
        migrations.AddField(
            model_name="post", name="date", field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post", name="slug", field=models.SlugField(unique=True),
        ),
    ]
